### ISSUE TITLE
Input fields that are invalid at startup don't show validationMessage

### ISSUE THREAD

**Issue by freudFlintstone** [mobily-enterprises/tpe#2]
If an input field has a required flag or a pattern that makes it invalid before user interaction, FormElementMixin does not set showValidationMessage, and we end up with an input that is invalid seemingly for no reason.

**Comment by mercmobily** [comment]
I left it this way because I thought it matched the native behaviour.
Native elements will only ever show a problem if they are run checkValidity() -- which will in turn emit the event @invalid which then, if not preventDefault()ed, will show the (ugly) native error message.
The nn-elements don't do anything other than catching that @invalid event and set the error message variable.

So, natively speaking, no checkValidity == no error message. However, the "invalid" state is already there.

When I saw it, it looked useful because it basically tells you which fields are there to be taken care of, but without bothering the user with an error message.

This can be changed -- namely, I can force en-form or nn-form to do a checkValidity after firstRender(). This could be optional too.

Let me know what you think.

**Comment by mercmobily** [comment]
Maybe you can answer this?

https://stackoverflow.com/questions/58035998/run-a-function-once-all-children-element-are-actually-updated

Doing this when there are native elements is _terrible_ because the result is that _one_ of them, the first one that doesn't satisfy validation, will show the bubble...

**Comment by mercmobily** [comment]
This is to be closed since I am 100% sure I replicate native behaviour which is what we want.
